
= Scratchy =
Rashid Khan
v0.1, 2013-11-18
:doctype: article

[preface]
== The Scratchy Way ==
Scratchy is a simple system for extracting user focused documentation from code. Scratch is not
for API docs, though it could be if you really wanted.
Scratchy enforces no particular format. It's purpose is to assemble the scattered parts of your
documentation in the order you specify, then drop them into a directory and file structure.

While scratchy doesn't force a particular format, there are some recommendations.
- Start every line in a comment with a specific character. Scratchy necessarily trims leading
whitespace to deal with indentation. If your formatter requires leading white space it will be
relative from your +--line+ argument

//index.js:2

=== Documentation Format ===

It is up to you to decide what format you wish to document in. If you were some kind of sadist
you could write your docs in HTML and skip the post processing
footnote:[Don't do that]
The Scratchy documentation uses Asciidoc because it serves as a powerful intermediary to many
other formats, but you could just as easily use something like Markdown.  From there you can use
whatever tool you'd like to post process them.
//index.js:46


=== Scratch tag ===

Scratchy does not want all of your comments. To denote doc blocks that scratchy should
extract, the opening of your comment should contain the +@scratch+ tag immediately following
the comment opening characters.
//index.js:91


=== Scratch path ===

The scratch path tells scratchy where to put the extracted documentation. The path is a
simple directory path, followed by an priority number. For example, +/intro/welcome/2+
would be written to your output directory, in the intro directory, in the 'welcome'
file. It would appear after +/intro/welcome/1+ if it existed. Gaps in
priority numbers are fine, as are duplicates. Of course
order is not guaranteed with duplicate priority numbers.
//index.js:148


==== Pre-existing files ====

Scratchy will not overwrite your exist docs, nor will ti append to them or try to merge
them. You will need to move your old docs out of the way. Scratchy will not abort, but
will communicate that it failed to write that path
//index.js:134


== Running Scratchy ==

Scratchy has only one required argument +--output+, to tell scratchy where to put the docs it
extracts. For example:

 scratchy -o docs

Would put the extracted docs into +./docs+. Here is the command we used to build the docs you are
reading right now:

 scratchy -uo docs -p scratchy

Scratchy is extracting documentation from itself! Spooky.
If you're wondering what those switches
do, see the link:../usage.html[Command Line reference]

//index.js:193


== Post-Processing ==

Scratchy is designed to promote post processing. Why? Because how can anyone know what format
you will want your documentation in, or for what purpose? Scratchy does not assume you're
writing API docs, nor does it assume that a web browser will be the destination for the
documentation it extracts. How you choose to post process is up to you.

==== How does scratchy do it? ====

Because the documentation for the Scratchy project is in ASCIIDoc, we have
the option of extracting it to HTML, PDF, ePub, and a host of other formats. Here is the command
we use to post process Scratchy's output:

  find docs -name *.txt | xargs -L 1 asciidoc -a numbered -b html5 -a icons -a toc2 -a theme=scratchy

//index.js:171

