== Command Line Reference ==


Scratchy takes a number of command line parameters to control how it parses your comments and
outputs files

[cols="1,2,2,10",options="header"]
|=======================================
| Short | Long | Default | Description
| -o | --output | *required* |
Directory in which to store extracted documentation. This will be created if it does not exist.
| -p | --pattern | '\**/*.js'|
File pattern to match when searching for source code. The default is to recursively search for
javascript files. Specified patterns must be quoted depending on how your shell treats globs
| -b | --begin | /** |
The string of characters that indicates a comment block is starting. These should be immediately
followed by @scratch /your/path/and/1234 in your code.
| -e | --end | */ |
String that indicates a comment block is ending
| -l | --line | * |
String at the beginning of every line in a comment block. Why? So that scratchy knows where
to begin considering white space to be important. Leaving this off a line allows you to make
comments within your comment blocks. OOooo.
| -s | --strip | <space> |
String to strip, along with the --line string, from the beginning of every line. Useful if you
trim trailing white space, but want blank lines to be considered
| -x | --extension | .txt |
Extension, with leading dot, to add to exported documents
| -u | --unslash | N/A |
Turn \/ into /
|=======================================
